.circleci/config.yml, CHANGELOG.md, README.md, lib/wasmex.ex, lib/wasmex/instance.ex, lib/wasmex/native.ex, mix.exs, mix.lock, native/wasmex/src/atoms.rs, native/wasmex/src/instance.rs, native/wasmex/src/lib.rs, native/wasmex/src/memory.rs, test/wasm_source/src/lib.rs, test/wasmex/instance_test.exs, test/wasmex_test.exs
This release brings is closer to a production-ready experience. 🎉 
Calls of WebAssembly functions are now handled asynchronously: Invoking a WASM function via `Instance.call_exported_function` calls our Rust NIF as before, but does not directly execute the function. Instead, a new OS thread is spawned for the actual execution. This allows us to spend only few time in the NIF code (as required by the Erlang VM). Once the WASM function in that thread returns, we send a message to the calling erlang process.
To ease handling, we converted our main module `Wasmex` into a `GenServer` so that a WASM function call can be used in a synchronous manner as before.
fixes #6
=> async WASM function calls

.gitmodules, native/wasmex/Cargo.toml
...to be able to compile against master more easily. This made it possible for me to use the branch as a hex dependency directly like: `{:wasmex, github: "myobie/wasmex", branch: "prototype_imports", submodules: true}`
_(I understand the dependency on wasmer master will go away in the future, so maybe this isn't worth merging if that is soon.)_
=> Adding wasmer as a submodule

lib/wasmex.ex, native/wasmex/src/atoms.rs, native/wasmex/src/instance.rs, native/wasmex/src/namespace.rs, test/wasm_import_test/src/lib.rs, test/wasmex_test.exs
Also into strings for the callback token.
This is my first contribution to a rust project, so I am sure what I've written isn't mergeable yet. If you have time to provide feedback then I can address any concerns. 
I decided to use atoms with the same names as the WASM types instead of ones like `:uint8` for memory. Those make sense for memory because the bytes need to be encoded, decoded from the heap, but since these are going onto the stack I think using the WASM types makes sense. However, I can change it if you think it's better to not leak the WASM implementation details out like that.
=> Decode import params and results into types

.circleci/config.yml, CHANGELOG.md, lib/wasmex.ex, lib/wasmex/memory.ex, native/wasmex/src/atoms.rs, native/wasmex/src/memory.rs, native/wasmex/src/namespace.rs, test/wasmex/instance_test.exs, test/wasmex_test.exs
* Refactor the rust-implementation of `memory` to not depend on an instance.
* Inject the instances memory into the callback context
=> Forward instance memory into elixir callbacks

README.md, lib/wasmex/memory.ex, lib/wasmex/native.ex, native/wasmex/src/lib.rs, native/wasmex/src/memory.rs, test/wasmex/memory_test.exs, test/wasmex_test.exs
* Writing binaries is no longer null terminated
* Reading binaries returns a charlist/bitstring depending on the bytes
* Reading binaries requires a length (I don't have many use cases where I want to consume the entire memory of the wasm vm)
* Reading strings reads a binary and pipes to `to_string`
Binaries are useful for communicating files or ciphers into/out of the wasm VM while strings are more useful for text communication so I think it's important to support both easily.
TODO:
If you get time, I'd appreciate your thoughts @tessi
=> New way to read and write binaries

native/wasmex/src/memory.rs, test/wasmex/memory_test.exs
The current `read`/`write_binary` functions only work with valid strings. This changes to use rustler's `Binary` for reading and writing / encoding and decoding. I'll be honest the for loop with the `binary[i - start]` is pretty ugly to me, but I couldn't think of a better way to do it.
=> Non-string binaries in memory

lib/wasmex/memory.ex
A small change to the type specs. Dialyzer isn't checking the `.exs` files so it didn't catch the tests where zero was used.
=> Memory indexes can be zero

native/wasmex/src/environment.rs, native/wasmex/src/instance.rs, native/wasmex/src/printable_term_type.rs
`Enum` in Rust seems to be right enough to store a value and a type together
=> Removing unsafe from value conversion

native/wasmex/.cargo/config
Hello, I am having trouble compiling Wasmex for my Aarch64-darwin CPU. When I run `mix test` on my project, I get the following error:
```
rustler::types::tuple::make_tuple::h8c2393e1a45d3d38 in librustler-8635bf1d8b765849.rlib(rustler-8635bf1d8b765849.rustler.e7e4hp6d-cgu.11.rcgu.o)
rustler::types::tuple::_$LT$impl$u20$rustler..types..Encoder$u20$for$u20$$LP$$RP$$GT$::encode::hf6cc205a13956d93 in librustler-8635bf1d8b765849.rlib(rustler-8635bf1d8b765849.rustler.e7e4hp6d-cgu.11.rcgu.o)
rustler::wrapper::tuple::make_tuple::hd5746784462fd12c in librustler-8635bf1d8b765849.rlib(rustler-8635bf1d8b765849.rustler.e7e4hp6d-cgu.15.rcgu.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
error: aborting due to previous …
```
=> Support `target.aarch64-apple-darwin`

CHANGELOG.md, README.md, lib/wasmex.ex, lib/wasmex/callback_token.ex, lib/wasmex/instance.ex, lib/wasmex/memory.ex, lib/wasmex/module.ex, lib/wasmex/native.ex, lib/wasmex/pipe.ex, native/wasmex/src/instance.rs, native/wasmex/src/lib.rs, native/wasmex/src/module.rs, test/test_helper.exs, test/wasi_test.exs, test/wasmex/instance_test.exs, test/wasmex/memory_test.exs, test/wasmex_test.exs
We used to compile and instantiate modules from .wasm files directly.
This step implicitly compiled a WASM module first, before actually instantiating it.
This PR makes these two steps explicit, by adding `Wasmex.Module.compile/1` and deprecating `Wasmex.Instance.from_bytes/2` and `Wasmex.Instance.wasi_from_bytes/3`.
It is still possible to start the Wasmex GenServer from bytes without deprecation.
But in addition to that, one can now start the GenServer modules from previously compiled modules.
This way, a module can be re-used as often as desired.
This change allows some great speed-ups. E.g. our test suite went from 14.5s runtime down to 0.2s (on my machine).
=> Split module compilation from instance creation

CHANGELOG.md, native/wasmex/src/instance.rs, native/wasmex/src/module.rs, test/wasmex_test.exs
* adds support for compiling modules from web assembly text format (WAT)
* removes the constraint of wasm modules needing to export memory
=> Support WAT and modules without exported memory

lib/wasmex/memory.ex
Correct the WebAssembly module linear memory page size in the docs.
=> Correct linear memory page size in Memory docs

.github/workflows/compatibility-elixir.yaml, CHANGELOG.md, README.md, mix.exs, native/wasmex/Cargo.lock, native/wasmex/Cargo.toml, test/wasm_import_test/Cargo.toml, test/wasm_test/Cargo.toml
- require at least elixir 1.11 (we attempt to support the last three elixir releases if possible)
- added changelog entries for the last couple of great contributions
- bump version to 0.7.0
fixes #324
=> Cleanups and version bump to 0.7.0

.github/workflows/release.yaml
> If you define both `branches`/`branches-ignore` and `paths`, the workflow will only run when both filters are satisfied.
https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#using-filters-to-target-specific-paths-for-pull-request-or-push-events
For the above reason, the `release` workflow did not run as expected.
related issue: https://github.com/tessi/wasmex/pull/326#issuecomment-1080170610
=> ci: fix release workflow trigger on file-changed and branches

CHANGELOG.md, lib/wasmex.ex, mix.exs
Fixes #332 
Hi! 👋🏻 We use Wasmex as the underlying Wasm wrapper for https://github.com/wasmCloud/wasmcloud-otp, and we allow users to configure a timeout for calling a Wasm function. In the interest of supporting that use case, I wanted to allow the `call_function` function to accept a timeout value.
I've kept the default value the same as https://hexdocs.pm/elixir/1.13/GenServer.html#call/3, with the same style of using a default value if the parameter isn't supplied. I also bumped a patch version, but please let me know if this doesn't conform to your semver strategy and I can remove that.
=> [FEAT] Allow users to configure a timeout value for call_function

.github/workflows/compatibility-elixir.yaml, .github/workflows/release.yaml, .github/workflows/rust-ci.yaml, .tool-versions, CHANGELOG.md, native/wasmex/Cargo.lock, native/wasmex/Cargo.toml
* updated wasmer to 2.3.0
* updated CI toolchain to OTP 25 (and dropped OTP 22)
* ignored failing clippy lint due to a lifetime issue in rustler
* updated rust code to the 2021 rust edition
* updated rust/typetag to 0.2.2
=> Dependency Updates

.github/workflows/compatibility-elixir.yaml, .github/workflows/elixir-ci.yaml, .github/workflows/release.yaml, .github/workflows/rust-ci.yaml, .gitignore, CHANGELOG.md, README.md, mix.exs, native/wasmex/.cargo/config, native/wasmex/Cross.toml
While building the 0.8.0 release I noticed some warning in our CI actions and build toolchain. This MR attempts to fix them -- all fixed in one MR and not on `main` because we all know CI needs several attempts to get right :)
=> Improve build/release toolchain

CHANGELOG.md, lib/wasmex/native.ex, lib/wasmex/store.ex, lib/wasmex/store_limits.ex, native/wasmex/Cargo.lock, native/wasmex/Cargo.toml, native/wasmex/src/store.rs, test/wasmex/store_test.exs
This allows users to limit resource usage (memory, table size, instance count) for Wasmex.Store. See Wasmex.StoreLimits for details.
Whenever resources such as linear memory, tables, or instances are allocated the `StoreLimits` are enforced.
=> Add support for setting Store limits

CHANGELOG.md, lib/wasmex/engine_config.ex, native/wasmex/src/atoms.rs, native/wasmex/src/engine.rs, test/wasmex/engine_config_test.exs, test/wasmex/engine_test.exs
It configures the Cranelift code generator optimization level.
Allows one of the following values:
* `:none` - No optimizations performed, minimizes compilation time by disabling most optimizations.
* `:speed` - Generates the fastest possible code, but may take longer.
* `:speed_and_size` - Similar to `speed`, but also performs transformations aimed at reducing code size.
=> Add option to EngineConfig to configure cranelift_opt_level

lib/wasmex.ex, native/wasmex/Cargo.lock, native/wasmex/Cargo.toml, native/wasmex/src/atoms.rs, native/wasmex/src/environment.rs, native/wasmex/src/instance.rs, native/wasmex/src/module.rs, native/wasmex/src/store.rs, test/wasmex/instance_test.exs, test/wasmex/module_test.exs
Wasmtime 22 changelog: https://github.com/bytecodealliance/wasmtime/blob/release-22.0.0/RELEASES.md
Closes: #575 
Closes: #576 
Closes: #577 
Closes: #580 
Closes: #583 
Closes: #588 
Closes: #589 
Closes: #590 
Closes: #591
=> Update to wasmtime v22.0.0

native/wasmex/Cargo.toml, native/wasmex/src/engine.rs, native/wasmex/src/environment.rs, native/wasmex/src/instance.rs, native/wasmex/src/lib.rs, native/wasmex/src/memory.rs, native/wasmex/src/module.rs, native/wasmex/src/pipe.rs, native/wasmex/src/printable_term_type.rs, native/wasmex/src/store.rs
@tessi I've cleaned up the features for rustler. The defaults include `nif_version_2_15` and `derive` is ignored and its functionality is unconditionally enabled [#621](https://github.com/rusterlium/rustler/pull/621).
=> Remove macro_use for rustler; Import missing derived structs

lib/wasmex/engine_config.ex, native/wasmex/src/engine.rs, test/wasmex/engine_config_test.exs, test/wasmex/engine_test.exs
I noticed that the `EngineConfig{}` doesn't support the `memory64` option offered by wasmtime. This PR adds support and tests for that.
Thanks for building wasmex!
=> feat: add support for wasmtime's underlying memory64 implementation

lib/wasmex.ex, test/wasmex_test.exs
Then we can call exported functions in imported functions.
=> Provide pid in imports callback context

native/wasmex/src/instance.rs, test/wasmex_test.exs
Function call errors into web assembly now have more detail if wasmtimes trap information is available. This helps, for example, when using `fuel` and the wasmtime store is out of fuel:
```
Error during function excecution (wasm trap: all fuel consumed by WebAssembly): error while executing at wasm backtrace:
0: 0x3618 - wasmex_test.wasm!void
```
The new information is added in parenthesis just after the `Error during function excecution` message.
See: #617
=> add wasmtime trap information on function call errors, if available

lib/wasmex/components.ex, test/components/components_test.exs
Very small PR to allow options to be a kw list for component GenServer. This makes it a little easier to add a component based genserver as a worker in application.ex. We might want to do the same for `Wasmex` I just didn't get to that yet :)
=> allow options to be a keyword list

native/wasmex/Cargo.lock, native/wasmex/Cargo.toml, native/wasmex/src/component_instance.rs, test/components/component_types_test.exs
We may or may not wish this to be configurable, but to start with having field names on records be atoms (when possible) seems reasonable.
=> record fields as atoms

lib/wasmex/components.ex, lib/wasmex/components/component.ex, lib/wasmex/components/component_server.ex, lib/wasmex/wasi/wasi_p2_options.ex, test/component_fixtures/hello_world.ex, test/components/component_server_test.exs
First pass at some docs, with Claude doing (most of) the writing and me batting cleanup ;)
=> Docs and refactoring

lib/wasmex.ex, lib/wasmex/instance.ex, lib/wasmex/store.ex, lib/wasmex/utils.ex, test/component_type_conversions_test.exs, test/wasi_test.exs, test/wasmex_test.exs
Adds support to pass an Instance to Wasmex.start_link. This is an attempt to allow serialised modules to be cached and be un-serialized later. This was only possible when users implemented their own GenServer, because the default Wasmex GenServer always instantiated a new module no matter what.
=> Support passing an Instance to Wasmex.start_link

.github/workflows/release.yml
fixes #774
We are building prebuilt binaries with too recent libraries (specifically glibc) and better roll back to an older available ubuntu build. Alternatives would be building with tailored docker containers - but this looks like the quick and easy win.
=> downgrade release binary build runners from ubuntu-latest to ubuntu-22.04

CHANGELOG.md, lib/wasmex/native.ex, lib/wasmex/wat.ex, native/wasmex/src/lib.rs, native/wasmex/src/wat.rs, test/wat_test.exs
useful for testing and quick demos
```
wat = """
(component
(core module $SumCoreWasm
(func (export "sum") (param $a i32) (param $b i32) (result i32)
local.get $a
local.get $b
i32.add
)
(memory (export "mem") 1)
(func (export "realloc") (param i32 i32 i32 i32) (result i32)
i32.const 0    
)
)
(core instance $sum_instance (instantiate $SumCoreWasm))
(func (export "sum") (param "a" s32) (param "b" s32) (result s32)
(canon lift
(core func $sum_instance "sum")
(memory $sum_instance "mem")
(realloc (func $sum_instance "realloc"))
)
)
)
"""
{:ok, wasm} = Wasmex.Wat.to_wasm(wat)
```
=> add support to compile wat files to wasm binaries
